### PR TITLE
Workaround for independent writes to Iterations in parallel, better detection of BP5 which in turn uncovers more instances of the first issue

### LINKED ISSUE #1616: Parallel flushing cannot rely on dirty checks
**Describe the bug**
Currently, our flushing logic checks iterations if they are dirty, i.e. have any data that needs to be flushed, and flushes them only then. This does not work reliably in parallel since even an independent write must be flushed collectively.

**To Reproduce**
No need for a reproducer, the reason for the behavior is known.

**Expected behavior**
Since we are currently moving towards improving our support for more general `Iteration::open()`/`Iteration::close()` workflows, our flushing logic should flush exactly those Iterations that are currently open instead of trying to outsmart the user by just flushing what we think needs to be flushed.
Until then, an intermediate solution would be to expose sth like `Iteration::markDirty()`.

**Additional context**
Found by @psychocoderHPC

### PR DESCRIPTION
**Pull request by franzpoeschel**
This somewhat fixes #1616 until we add a better solution. With this PR: `seriesFlush()` will always flush the containing Iteration if called from within an Iteration (and will ignore missing `dirty` annotations).

At the same time, I added a better detection for BP5-specific features. Since this means that `adios2::Engine::PerformDataWrite()` is used automatically more often, this uncovers further parallel flushing bugs. So, these two items are treated together in this PR.

In a follow-up PR later on, as a more breaking change, we would also flush all open iterations in MPI-parallel contexts on `series.flush()`, but for this we will first need functionality to reopen iterations after close #1592.

TODO:

- [x] documentation
- [x] testing

### CODE REVIEW

File: test/ParallelIOTest.cpp [hunk 1]
```diff
@@ -946,10 +946,16 @@ void hipace_like_write(std::string const &file_ending)
     int const last_step = 100;
     int const my_first_step = i_mpi_rank * int(local_Nz);
     int const all_last_step = last_step + (i_mpi_size - 1) * int(local_Nz);
+
+    bool participate_in_barrier = true;
```
Comment (franzpoeschel) [inline test/ParallelIOTest.cpp:1035]: @ax3l Can you please check if this bug also affects Hipace? Currently, the sequence of barriers and flushes dont match from rank to rank. This was uncovered only now, since flushing is effectively not collective in many situations, but this test now uses `adios2::Engine::PerformDataWrite()` of BP5 which is a bit stricter there.

Comment (ax3l) [reply test/ParallelIOTest.cpp:1035]: Ok, great catch!

For HiPACE++, we changed the time stepping logic the other year, so that every MPI rank just writes to exactly one iteration. Thus, it cannot have this bug (anymore).

**Review by ax3l — APPROVED** [review]
