### PR TITLE
Differentiate accessTypes on use

### LINKED ISSUE #394: Read-Only on Files Without Write Permissions
**Describe the bug**
Opening a `Series` as read-only does not work on files that do not have write permission for the user under Linux.

**To Reproduce**

Terminal:
```bash
$ chmod u-w simData_5000.h5

$ h5ls -v tmp_dir/simData_5000.h5 
Opened "tmp_dir/simData_5000.h5" with sec2 driver.
# ...

$ python -c 'import openPMD; openPMD.Series("simData_%T.h5", openPMD.Access_Type.read_only)'
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 990 in H5F_open(): unable to open file: time = Wed Nov 14 14:25:54 2018
, name = 'tmp_dir/simData_5000.h5', tent_flags = 1
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'tmp_dir/simData_5000.h5', errno = 13, error message = 'Permission denied', flags = 1, o_flags = 2
    major: File accessibilty
    minor: Unable to open file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Failed to open HDF5 file tmp_dir/simData_5000.h5
```

**Expected behavior**
Read-only files should be readable with only read-permissions.
`h5dump` and `h5ls` seem to work with those as well.

**Software Environment:**
 - version of openPMD-api: 0.6.3-alpha
 - installed openPMD-api via: pip (sdist; compiled from source)
 - operating system: Ubuntu 14.04.5 LTS "trusty"
 - machine: Hypnos (HZDR)
 - name and version of Python implementation: CPython 3.6.2
 - version of HDF5: 1.8.14
 - version of ADIOS1: none
 - name and version of MPI: none

**Additional context**
First seen in #390

### PR DESCRIPTION
**Pull request by anokfireball**
For frontend, use a seperate accessType variable that may change during the first read of a fileBased Series (required for setting values in case of READ_ONLY).
For the backend, continue using the same immutable accessType as before (desired by the user).

Fix #394.

### CODE REVIEW

File: include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp [hunk 1]
```diff
@@ -288,7 +288,7 @@ namespace openPMD
         std::shared_ptr< FILEHANDLE > getFilehandle(
             File,
             AccessType accessType
-        ); //, AccessType accessType=this->m_handler->accessType);
+        ); //, AccessType accessTypeFrontend=this->m_handler->accessTypeFrontend);
```
Comment (anokfireball) [inline include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp:291]: @franzpoeschel Is this code safe to remove?

**Comment by ax3l** [comment]
@C0nsultant thanks, that's way less intrusive than my multi-month refactoring in #395 :D

Can you please cherry-pick https://github.com/openPMD/openPMD-api/pull/395/commits/2e07d32bb98d1cfebf782f990541748b475d1b43 on this?

**Comment by anokfireball** [comment]
It was ~probably~ certainly not your top priority, given the circumstances and the rarity of the problem. 
This essentially duplicates the `init` logic from your PR, but requires only an additional variable instead of new function calls, branches and changed function interfaces.

Let's see if it's enough. Local tests were successful at least :)

**Comment by ax3l** [comment]
I admittedly invested quite some time ;-)
We should make debugging on `flush` more easy somehow, added a ton of printf diagnostics to get an idea what's going on when things fail.

**Comment by anokfireball** [comment]
It's one ugly bug resulting from one ugly hack, no need to conceal the truth.
Hope you did not lose to much of your temper during the multi-month refactoring :)

> We should make debugging on `flush` more easy

I can see why it is tough to get the flow of events during this mystical call. How do you think it could be improved (i.e. what interests you about the call and what doesn't)?

**Comment by anokfireball** [comment]
~Btw, this issue was introduced in #352 to _comply with our IO documentation_. :laughing:~

What was written here was actually :hankey:.

**Comment by ax3l** [comment]
> Hope you did not lose to much of your temper during the multi-month refactoring :)

Nah, l met nearly every part of our middleware now, so that was a good recap for me #positiveThinking

**Comment by ax3l** [comment]
> I can see why it is tough to get the flow of events during this mystical call. How do you think it could be improved.

We abstracted it quite far so that many IOTasks can not be identified with simple names anymore. What I found helpful is to add debug info to the task switch boards in `AbstractIOHandlerImpl` and potentially their equivalents in `ADIOS1IOHandler`/`HDF5IOHandler`/`JSONIOHandler`.

**Comment by ax3l** [comment]
@C0nsultant gitter?

**Review by ax3l — APPROVED** [review]
<3 savior!

File: include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp (hunk 1 above)
Comment (ax3l) [reply include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp:291]: @franzpoeschel ping. can we I merge this?

Comment (ax3l) [reply include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp:291]: @franzpoeschel I will merge this for now, but you can post here and we can do follow-up PRs to `dev` is something is off :)
