### PR TITLE
Don't flush Series a second time after throwing an error

### LINKED ISSUE #1006: Series flushed twice if error occurs
When some error happens during `Series::flush()`, C++ will destroy all objects currently found on the stack, including the instance `Series`. `Series::~Series()` calls `Series::flush()`. Consequence: An error happening during `Series::flush()` will lead to `Series::flush()` being attempted a second time, on a broken object, often leading to completely different and mostly unrelated error messages.

This is annoying during development, I've often wasted time now looking into the wrong error that wasn't actually the problem. I imagine, having unrelated, seemingly random error messages is often not the best user experience either.

Suggestion: In `Series::flush`, catch any error, set a flag `unhandledError` or something. If that flag is found, the destructor does not call `Series::flush()`.

### PR DESCRIPTION
**Pull request by franzpoeschel**
Fix #1006. Remember in a flag whether the last flush was successful. If it was not, don't flush again upon `Series::~Series`.

Example: `close_iteration_test` was very noisy until now since it deliberately left the `Series` in an invalid state:
```
Filters: close_iteration_test
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
[~Series] An error occurred: [Series] Detected illegal access to iteration that has been closed previously.
```

After this PR:
```
Filters: close_iteration_test
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
openPMD series: close_iterations_%T
openPMD standard: 1.1.0
openPMD extensions: 0

number of iterations: 2

number of meshes: 1

number of particle species: 0
```

### CODE REVIEW

File: include/openPMD/Series.hpp [hunk 1]
```diff
@@ -349,7 +350,8 @@ class SeriesImpl : public AttributableImpl
     std::future< void > flush_impl(
```
Comment (ax3l) [inline include/openPMD/Series.hpp:361]: Can you please add a doxygen string here, describing the parameters?

Do we really need a new parameter or can we access the member variable directly? It looks like we pass `true` most of the time?

File: src/Series.cpp [hunk 2]
```diff
@@ -1223,28 +1236,8 @@ SeriesImpl::advance(
...
-        }
-        IOHandler()->m_flushLevel = oldFlushLevel;
-    }
-    catch( ... )
-    {
-        IOHandler()->m_flushLevel = oldFlushLevel;
-        throw;
-    }
+    flush_impl(
+        begin, end, FlushLevel::UserFlush, /* flushIOHandler = */ false );
```
Comment (ax3l) [inline src/Series.cpp:1242]: Why don't we flush the IOHandler at this point?
Needs an inline comment, this gets quite involved.

File: include/openPMD/Series.hpp (hunk 1 above)
Comment (franzpoeschel) [reply include/openPMD/Series.hpp:361]: > Do we really need a new parameter or can we access the member variable directly? It looks like we pass true most of the time?

This is not the new flag that I added. I needed to add this parameter so I could call `flush_impl()` from within `advance()`. This way, all flushing goes through `flush_impl()`, allowing me to add this logic here only once.

File: src/Series.cpp (hunk 2 above)
Comment (franzpoeschel) [reply src/Series.cpp:1242]: I've added/clarified the comment now. Note that the logic of `advance` hasn't changed, it was just so far a slightly modified manual version of `flush_impl()`, but I have now added this workflow to `flush_impl()`.

File: include/openPMD/Series.hpp [hunk 3]
```diff
@@ -346,10 +347,22 @@ class SeriesImpl : public AttributableImpl
...
+     * @param level Flush level, as documented in AbstractIOHandler.hpp.
+     * @param flushIOHandler Tasks will always be enqueued to the backend.
+     *     If this flag is true, tasks will be flushed to the backend.
+     */
     std::future< void > flush_impl(
         iterations_iterator begin,
         iterations_iterator end,
-        FlushLevel );
+        FlushLevel level,
+        bool flushIOHandler );
```
Comment (ax3l) [inline include/openPMD/Series.hpp:365]: Do we want to add `= true` as default parameter, since this is usually what we need and expect?
That was the old behavior and seems logical that `flush_impl()` calls `flush()`?

That way we could also keep all but one call to it unchanged.

What do you think?

File: include/openPMD/Series.hpp (hunk 1 above)
Comment (ax3l) [reply include/openPMD/Series.hpp:361]: I don't understand :)
Isn't `bool flushIOHandler` the new flag?

**Comment by ax3l** [comment]
The current doc update already helps - let's discuss the leftover question in person in our next meeting :)

Thanks again for the fix!

**Review by ax3l — APPROVED** [review]

File: include/openPMD/Series.hpp (hunk 1 above)
Comment (franzpoeschel) [reply include/openPMD/Series.hpp:361]: `bool flushIOHandler` and `bool SeriesData::m_lastFlushSuccessful` are two different things. `flushIOHandler` is not manipulated, only read.

File: include/openPMD/Series.hpp (hunk 3 above)
Comment (franzpoeschel) [reply include/openPMD/Series.hpp:365]: On the one hand, I like to keep those things explicit in internal usage (example: I already had a merge conflict where I had added different flags to the same function, but since those flags had no defaults, git showed me the conflict for each invocation, making things easier to fix). 
However, there's a very clear call for a default in this instance, so I can do a follow-up PR and add it if you like?

File: include/openPMD/Series.hpp (hunk 1 above)
Comment (ax3l) [reply include/openPMD/Series.hpp:361]: discussed offline :+1:

File: include/openPMD/Series.hpp (hunk 3 above)
Comment (ax3l) [reply include/openPMD/Series.hpp:365]: Sounds good!
