### PR TITLE
Fail fast during flush of empty Records

### LINKED ISSUE #287: Record creation implies non-scalar RecordComponents
When creating a ```Record``` without supplying any ```RecordComponents```, ```Record::m_containsScalar``` is [default](https://github.com/openPMD/openPMD-api/blob/4832b11a91a70a9a6b7d91e119222fb02602b5ea/include/openPMD/backend/BaseRecord.hpp#L86)-initialized to ```false```. Under this assumption, an [empty group](https://github.com/openPMD/openPMD-api/blob/aca17f8563e53841b3bbb44a05a2a9e7cb3afb7d/src/Record.cpp#L60-L76) is created for such ```Record```s on ```Series::flush()```.

With major backends (e.g. [ADIOS](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L355-L367)) lacking node deletion entirely, this assumption is a design-flaw: The user can not at a later point resolve the ambiguity by specifying the ```RecordComponent``` as ```SCALAR```. This would lead to a [```std::runtime_error```](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L359) as the empty group can not reliably be replaced with a dataset.

To solve this, we should not make assumptions about (non-)scalar components. This means that we must not flush ```Record```s that contain no ```RecordComponents```. There are two options for reporting this to the user:
 - (preferred) ```throw``` when a ```Series::flush()``` reaches an empty ```Record```
 - (not preferred) skip the ```Record```; only create a dataset or group when the ambiguity is removed. When there is no such ```RecordComponent``` on file closing, this will silently discard the ```Record```.

### PR DESCRIPTION
**Pull request by anokfireball**
Do not write write records to disk unless scalar/non-scalar ambiguity is resolved. This is done when the user creates a record component that is either scalar/nonscalar and possibly constant.

Also fixes major bugs in the ADIOS1 backend concerning ```fileBased``` output.

Closes #287.

### CODE REVIEW

File: src/backend/MeshRecordComponent.cpp [hunk 1]
```diff
@@ -44,10 +44,16 @@ MeshRecordComponent::read()
     Attribute a = Attribute(*aRead.resource);
     if( *aRead.dtype == DT::VEC_FLOAT )
         setPosition(a.get< std::vector< float > >());
+    else if( *aRead.dtype == DT::FLOAT )
+        setPosition(std::vector< float >(a.get< float >()));
```
Comment (anokfireball) [inline src/backend/MeshRecordComponent.cpp]: This actually initializes a vector with
```cpp
static_cast< std::vector< float >::size_type >(a.get< float >())
```
default-initalized elements.
The intended behaviour is realized with
```cpp
setPosition(std::vector< float >({a.get< float >()}));
```

Comment (ax3l) [reply src/backend/MeshRecordComponent.cpp]: @C0nsultant do you want to update the branch with it?

File: src/backend/MeshRecordComponent.cpp [hunk 2]
```diff
@@ -44,10 +44,16 @@ MeshRecordComponent::read()
...
     else if( *aRead.dtype == DT::VEC_DOUBLE )
         setPosition(a.get< std::vector< double > >());
+    else if( *aRead.dtype == DT::DOUBLE )
+        setPosition(std::vector< double >(a.get< double >()));
```
Comment (ax3l) [inline src/backend/MeshRecordComponent.cpp]: same here

File: src/backend/MeshRecordComponent.cpp [hunk 3]
```diff
@@ -44,10 +44,16 @@ MeshRecordComponent::read()
...
     else if( *aRead.dtype == DT::VEC_LONG_DOUBLE )
         setPosition(a.get< std::vector< long double > >());
+    else if( *aRead.dtype == DT::LONG_DOUBLE )
+        setPosition(std::vector< long double >(a.get< long double >()));
```
Comment (ax3l) [inline src/backend/MeshRecordComponent.cpp]: same here

File: test/SerialIOTest.cpp [hunk 4]
```diff
@@ -1451,9 +1443,11 @@ TEST_CASE( "adios1_fileBased_write_test", "[serial][adios1]" )
     {
         *positionOffset_local_1 = positionOffset_global[i];
         e_1["positionOffset"]["x"].storeChunk({i}, {1}, positionOffset_local_1);
-        o.flush();
     }
 
+    //TODO breaks openWriteFile logic when removed
+    //o.flush();
```
Comment (ax3l) [inline test/SerialIOTest.cpp]: works now?

File: examples/1_structure.cpp [hunk 5]
```diff
@@ -47,5 +47,10 @@ int main()
     Dataset dataset = Dataset(Datatype::DOUBLE, Extent{1});
     mass_scalar.resetDataset(dataset);
 
+    /* Required Records and RecordComponents are created automatically.
+     * Initialization has to be done explicitly by the user. */
+    electrons["position"][RecordComponent::SCALAR].resetDataset(dataset);
```
Comment (ax3l) [inline examples/1_structure.cpp:52]: I just realized `resetDataset` in `(Patch)RecordComponent` lacks doxygen docs. What does it do, overwrite a dataset?

File: test/SerialIOTest.cpp (hunk 4 above)
Comment (anokfireball) [reply test/SerialIOTest.cpp]: No, unfortunately. I figured out where it all goes haywire, but not what causes the behavior.
It has to do with ADIOS's distinction between read/write files. The scenario under which I can reproduce this is when creating a ```fileBased``` Series and *not* flushing between creation of two Iterations (i.e. files). The problem then becomes that the file with the earliest creation time will have an on-disk size of 0Bytes and only the last file will be created as expected.
I doubt this is a problem with ADIOS itself, but the way the backend is using it:
File creation (i.e. opening a write file) is deferred until required (i.e. encountering a Dataset write operation). This might be a problem if no Dataset write occurs. Once this file is opened, it will not be closed until new defines or reads happen.
... and this is exactly where the problem happens. One of these calls happens at the wrong time (for ADIOS), so the file on disk will be empty. Unfortunately, ADIOS doesn't fail (only warns) when opening a 0Byte file (```adios_errno``` is not set, either). The ```SIGSEGV``` in the test happens when that faulty file is closed.

File: src/backend/MeshRecordComponent.cpp (hunk 1 above)
Comment (anokfireball) [reply src/backend/MeshRecordComponent.cpp]: Will do before merging.

File: examples/1_structure.cpp (hunk 5 above)
Comment (anokfireball) [reply examples/1_structure.cpp:52]: It overwrites the default Dataset (single ```char```) with a user-defined dataset, including datatype, extent, chunking, compression, etc.
The Dataset is used when flushing a RecordComponent to disk, see [```RecordComponent::flush()```](https://github.com/openPMD/openPMD-api/blob/7501e3435913216812f3efe8707b30892b3aa915/src/RecordComponent.cpp#L97-L106) for example.

Comment (anokfireball) [reply examples/1_structure.cpp:52]: At this point I am not sure if a default *valid* dataset is the best solution. It surely is helpful for prototyping, but having a ```flush()``` fail with an uninitialized, default dataset sends a clear message.

File: test/SerialIOTest.cpp (hunk 4 above)
Comment (anokfireball) [reply test/SerialIOTest.cpp]: (Likely) found the culprit:
In ```fileBased``` Series, *one* ADIOS group was used for *all* files. This works when only one file is open at a time, but that is not a constraint enforced in the ADIOS backends.
A solution is to create a group for every file handle. The commit alleviates the CI failure, but does not reliably use the group across the backend yet.

**Comment by anokfireball** [comment]
@ax3l OSX builds on Travis are failing after an upgrade to High Sierra. In particular, spack install of a compiler [fails](https://travis-ci.org/openPMD/openPMD-api/jobs/410981935#L949):
```
=> Error: No compilers found for operating system highsierra and target x86_64.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	sierra-x86_64
	ubuntu14.04-x86_64
Run 'spack compiler find' to add compilers.
```
Can you look into that?

**Comment by ax3l** [comment]
> OSX builds on Travis are failing after an upgrade to High Sierra

ugh, sorry about that. yes will update: #299

ref: https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce

**Comment by anokfireball** [comment]
There is a pretty major blocker in the current ADIOS backend:
Attributes may only be defined *once* when using ```adios_define_attribute_byvalue()```. Otherwise, they will occur multiple times under multiple IDs.
The problem is that (borrowing from HDF5 behaviour), the backend was implemented under the assumption that successive definitions overwrite previous values.

```cpp
#define _NOMPI
#include <adios.h>


int main()
{
  adios_init_noxml(MPI_COMM_NULL);

  int64_t m_adios_group;
  int64_t m_adios_file;

  adios_declare_group(&m_adios_group, "att_test.bp", "", adios_stat_default);
  adios_select_method(m_adios_group, "POSIX", "", "");

  /* ############################################################################################################ */

  int i = 0;
  adios_define_attribute_byvalue(m_adios_group,
                                 "attribute", "/foo", adios_integer, 1, &i);

  i = 1;
  adios_define_attribute_byvalue(m_adios_group,
                                 "attribute", "/foo", adios_integer, 1, &i);

  /* ############################################################################################################ */

  adios_open(&m_adios_file, "att_test.bp", "att_test.bp", "w", MPI_COMM_NULL);
  adios_close(m_adios_file);

  adios_finalize(0);
  return 0;
}
```

leads to

```bash
 $ bpdump att_test.bp
[...]
 Attributes Count: 5
                Attribute Name (ID): attribute (1)
                Attribute Path: /foo
                Datatype: integer
                # of elements:   1
                Length in bytes: 4
                Value: 0

                Attribute Name (ID): attribute (2)
                Attribute Path: /foo
                Datatype: integer
                # of elements:   1
                Length in bytes: 4
                Value: 1
[...]
```

There are two options to explore for solving this problem:
- Deferring *all* attribute writes until the IOHandler is terminated. At that point we can determine which write happens last and discard all overwritten values.
- Using ```adios_define_attribute``` and write the attribute value to a variable. This is similar to what the backend already does for dynamic chunk sizes. Note ADIOS [doc](https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf):
> It is not appropriate to define a foating-point type attribute with high-precision, and cannot be used to define an array attribute. For those cases, see the next function below, ```adios_define_attribute_byvalue```.

**Comment by ax3l** [comment]
The first approach looks more forward-thinking, e.g. for other backends that will have similar limitations.

File: src/IO/ADIOS/ADIOS1IOHandler.cpp [hunk 6]
```diff
@@ -48,32 +48,30 @@ ADIOS1IOHandlerImpl::ADIOS1IOHandlerImpl(AbstractIOHandler* handler)
...
+        for( auto& group : m_attributeWrites )
+            for( auto& att : group.second )
+                flush_attribute(group.first, att.first, att.second);
+
+        /* create all files, even if ADIOS file creation has been deferred,
+         * but execution of the deferred operation has never been triggered
+         * (happens when no Operation::WRITE_DATASET is performed) */
+        for( auto& f : m_filePaths )
+            if( m_openWriteFileHandles.find(f.second) == m_openWriteFileHandles.end() )
+                m_openWriteFileHandles[f.second] = open_write(f.first);
```
Comment (anokfireball) [inline src/IO/ADIOS/ADIOS1IOHandler.cpp:70]: ~For this to work with ```AccessType::READ_WRITE```, [```openFile()```](https://github.com/openPMD/openPMD-api/blob/2cc1cef79f9b75d181296956611dc6acd2aaed3f/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L453-L487) needs to set ```m_existsOnDisk``` so [```open_write()```](https://github.com/openPMD/openPMD-api/blob/2cc1cef79f9b75d181296956611dc6acd2aaed3f/src/IO/ADIOS/ADIOS1IOHandler.cpp#L247-L281) does not overwrite, but append.~
Done.

**Comment by anokfireball** [comment]
@ax3l Should be ready for review. I'll add a few more tests and a changelog for the recent PRs today.

File: src/IO/ADIOS/ADIOS1IOHandler.cpp [hunk 7]
```diff
@@ -43,38 +43,35 @@ namespace openPMD
...
+
+        for( auto& f : m_openWriteFileHandles )
+            close(f.second);
+    }
```
Comment (anokfireball) [inline src/IO/ADIOS/ADIOS1IOHandler.cpp:74]: ~This needs to be done in ```ParallelADIOS1IOHandler.cpp``` as well.~
Done.

File: include/openPMD/ParticleSpecies.hpp [hunk 8]
```diff
@@ -62,11 +62,11 @@ namespace traits
 
             auto& np = ret.particlePatches["numParticles"];
             auto& npc = np[RecordComponent::SCALAR];
-            npc.resetDataset(Dataset(Datatype::UINT64, {0}));
+            npc.resetDataset(Dataset(Datatype::UINT64, {1}));
```
Comment (ax3l) [inline include/openPMD/ParticleSpecies.hpp:65]: Why do we set an extend of `1` here already? Doesn't this imply a first entry already? What if someone does not write data / writes exactly one entry later on? Just wondering about corner cases.

File: src/IO/ADIOS/ADIOS1IOHandler.cpp (hunk 6 above)
Comment (ax3l) [reply src/IO/ADIOS/ADIOS1IOHandler.cpp:70]: But does `openFile()` set this now?

File: src/IO/ADIOS/ADIOS1IOHandler.cpp (hunk 7 above)
Comment (ax3l) [reply src/IO/ADIOS/ADIOS1IOHandler.cpp:74]: done as far as I can see :)

File: src/IO/ADIOS/ADIOS1IOHandler.cpp [hunk 9]
```diff
@@ -301,6 +293,19 @@ ADIOS1IOHandlerImpl::open_read( std::string const& name )
     return f;
 }
 
+int64_t
+ADIOS1IOHandlerImpl::initialize_group(std::string const &name)
+{
+    int status;
+    int64_t group;
+    ADIOS_STATISTICS_FLAG noStatistics = adios_stat_no;
```
Comment (ax3l) [inline src/IO/ADIOS/ADIOS1IOHandler.cpp:301]: just a note: these statistics are quite interesting, but I never evaluated the RT costs in our use cases, so we turned them off by default.

if we could control from the outside we could evaluate them.

maybe good for an issue.

File: src/RecordComponent.cpp [hunk 10]
```diff
@@ -103,6 +104,21 @@ RecordComponent::flush(std::string const& name)
                 dCreate.compression = m_dataset->compression;
                 dCreate.transform = m_dataset->transform;
                 IOHandler->enqueue(IOTask(this, dCreate));
+                if( m_chunks->empty() )
+                {
+                    /* Ensure at least one WRITE_DATASET per dataset occurs
+                     * ADIOS1 backend only creates a dataset after at least once cell has been written */
```
Comment (ax3l) [inline src/RecordComponent.cpp:110]: do we or ADIOS define the term cell?

File: test/CoreTest.cpp [hunk 11]
```diff
@@ -102,8 +102,11 @@ TEST_CASE( "output_constructor_test", "[core]" )
 
     o.setMeshesPath("customMeshesPath").setParticlesPath("customParticlesPath");
 
-    o.iterations[1].meshes["foo"];
-    o.iterations[1].particles["bar"];
+    o.iterations[1].meshes["foo"]["baz"].resetDataset(Dataset(Datatype::DOUBLE, {1}));
```
Comment (ax3l) [inline test/CoreTest.cpp:105]: can you add a (global) extend-zero write to the tests and it's defined behaviour? Basically `empty_record_test` but where the user sets the extend explicitly to `{0}`?

Do we already have a test that does a parallel write with extend > 0 (1D and ND) in which some of the MPI ranks contribute *locally* zero extends? This is quite often the case for e.g. particle data.

**Review by ax3l — COMMENTED** [review]
Thank you so much, these are fantastic updates :sparkles: 

I have added some inline questions, probably most of them already addressed.

File: src/IO/ADIOS/ADIOS1IOHandler.cpp (hunk 6 above)
Comment (anokfireball) [reply src/IO/ADIOS/ADIOS1IOHandler.cpp:70]: Yes it does, right [here](https://github.com/openPMD/openPMD-api/blob/414f2ddbdd1e0542d6f82aa32885e3adbfe7eef4/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L490).

File: include/openPMD/ParticleSpecies.hpp (hunk 8 above)
Comment (anokfireball) [reply include/openPMD/ParticleSpecies.hpp:65]: ADIOS does not handle datasets without extent well. The default here is just used to enforce standard compliance and create deterministic behaviour across backends.
To address your concern about corner cases: [```PatchRecordComponent::resetDataset()```](https://github.com/openPMD/openPMD-api/blob/0.3.1-alpha/src/backend/PatchRecordComponent.cpp#L33-L42) should be used by users that do want to write actual data. It ~will~ should be replaced when writing production data.
If the user does *not* write dataset values ever, the created dataset will contain one potentially [default](https://github.com/openPMD/openPMD-api/blob/414f2ddbdd1e0542d6f82aa32885e3adbfe7eef4/src/RecordComponent.cpp#L107-L121)-initalized value.

File: src/RecordComponent.cpp (hunk 10 above)
Comment (anokfireball) [reply src/RecordComponent.cpp:110]: Interesting. ADIOS *does* use the same lingo for what I called cell. (See e.g. [```adios_define_mesh_unstructured```](https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf) on page 52).
I used it independently here, though.

File: test/CoreTest.cpp (hunk 11 above)
Comment (anokfireball) [reply test/CoreTest.cpp:105]: You're probably misreading what is happening here.
```resetDataset()``` is not actually a data write-through to disk. It *defines* the *global* datatype, extent, compression (...) of each dataset. This is a collective call, every rank will have to call this with the same global data.
If the extent passed to ```resetDataset()``` is zero in any dimension (and is later flushed to disk), undefined behaviour in certain backends ensures.

Where you would actually pass the zero-extent in the scenario you're describing is in [```RecordComponent::storeChunk()```](https://github.com/openPMD/openPMD-api/blob/0.3.1-alpha/include/openPMD/RecordComponent.hpp#L167-L196), which triggers a ```Operation::WRITE_DATASET``` in the backends (see [HDF5](https://github.com/openPMD/openPMD-api/blob/0.3.1-alpha/src/IO/HDF5/HDF5IOHandler.cpp#L653-L735) and [ADIOS](https://github.com/openPMD/openPMD-api/blob/0.3.1-alpha/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L376-L416)).

#135 is for implementing such a local zero-extent write into a global dataset. Currently, there is no such test.

Comment (ax3l) [reply test/CoreTest.cpp:105]: Ok, great. Just one thing:

> If the extent passed to resetDataset() is zero in any dimension (and is later flushed to disk), undefined behaviour in certain backends ensures.

Instead of undef behaviour, depending on backend, can we just implement defined similar behaviour for all backends? E.g., if global zero extent is given we throw (directly or in flush) or if zero is given we skip the write (and document that), etc.?

**Review by ax3l — APPROVED** [review]
Very nice! We can define a consistent behavior for global-zero extends in a follow-up.

File: test/CoreTest.cpp (hunk 11 above)
Comment (anokfireball) [reply test/CoreTest.cpp:105]: > if global zero extent is given we throw (directly or in flush)

That's the behaviour I currently implement in #309. Skipping the undefined write (however verbose) does not appeal to me, as the dataset itself does not really make sense.
