### PR TITLE
Iteration::open()

### LINKED ISSUE #856: Read from one (out of many) ranks.
**Describe the bug**
Unable to open a  file-based series in an MPI program, then read from one of the rank. E.g . rank 0. 

**To Reproduce**
Compile-able/executable code example to reproduce the problem:

```C++
#include <openPMD/openPMD.hpp>
#include <mpi.h>

#include <iostream>
#include <memory>
#include <cstddef>


using std::cout;
using namespace openPMD;

int main(int argc, char *argv[])
{
    MPI_Init(&argc, &argv);

    int mpi_size;
    int mpi_rank;

    MPI_Comm_size(MPI_COMM_WORLD, &mpi_size);
    MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
 {
        Series series = Series(
            "../samples/8a_parallel_3Db_%T.bp",
            Access::READ_ONLY, MPI_COMM_WORLD);            

        MeshRecordComponent E_x = series.iterations[1].meshes["B"]["x"];

        Offset chunk_offset = {
          static_cast< long unsigned int >(mpi_rank) + 1, 1, 1
        };
        Extent chunk_extent = {2, 2, 1};

        if (0 == mpi_rank) 
          {
            auto chunk_data = E_x.loadChunk<double>(chunk_offset, chunk_extent);
            series.flush();        
          }
    }

    MPI_Finalize();

    return 0;
}

// ...
```

**Expected behavior**
when running with 1 rank,  read is successful. 
when running with 2 ranks,  hangs.  
Reason: 
when  Series is opened for reading , Series.cpp's readFileBased() is called (by all ranks).  This functions issues fClose upon finishes.  When Rank 0 wants to read a variable, readFileBased is invoked by rank 0 upon flush().  Which then tries to open the iteration again.  However because Rank 1 is inactive, open, a collective call,  can not proceed successfully. 

**Software Environment**
 current with 
 - version of ADIOS2: [e.g. 2.6.0]
 (did not check with H5)

### PR DESCRIPTION
**Pull request by ax3l**
Fix #856

### CODE REVIEW

File: src/Iteration.cpp [hunk 1]
```diff
@@ -174,6 +175,24 @@ Iteration::close( bool _flush )
...
+Iteration &
+Iteration::open()
+{
+    Series * s = &auxiliary::deref_dynamic_cast< Series >(
+        parent->attributable->parent->attributable );
+    // figure out my iteration number
+    auto begin = s->indexOf( *this );
+    //auto end = begin;
+    //++end;
+    s->openIteration( begin->first, *this );
```
Comment (ax3l) [inline src/Iteration.cpp]: Something is still wrong here, because it still hangs in the test.

File: test/ParallelIOTest.cpp [hunk 2]
```diff
@@ -547,6 +547,102 @@ TEST_CASE( "close_iteration_test", "[parallel]" )
...
+    // check non-collective, parallel read
+    {
+        Series read( name, Access::READ_ONLY, MPI_COMM_WORLD );
+        Iteration it = read.iterations[ 30 ];
+        it.open(); // collective
+        if( mpi_rank == 0 ) // non-collective branch
+        {
+            auto E_x = it.meshes["E"]["x"];
+            auto data = E_x.loadChunk< double >();
+            read.flush();
```
Comment (ax3l) [inline test/ParallelIOTest.cpp:634]: expected hang here that we try to fix with `it.open()`

File: src/Iteration.cpp [hunk 3]
```diff
@@ -174,6 +175,24 @@ Iteration::close( bool _flush )
...
+    //s->flush_impl( begin, end ); // does not work as expected
+    //s->flush(); // does not work as expected
+    this->flush();
+    IOHandler->flush();
```
Comment (franzpoeschel) [inline src/Iteration.cpp]:
```suggestion
    // figure out my iteration number
    auto begin = s->indexOf( *this );
    auto end = begin;
    ++end;
    // set dirty, so Series::flush will open the file
    this->dirty() = true;
    s->flush_impl( begin, end );
    this->dirty() = false;
```

`Series::openIteration` is for opening an iteration's file in file-based layout, so that will likely break if using group-based iteration layout.

File: src/Iteration.cpp (hunk 1 above)
Comment (franzpoeschel) [reply src/Iteration.cpp:187]: The hang is at the backends' fault i think. I've pushed a quick fix for ADIOS2, but I think ADIOS1 needs to be fixed too.

**Review by franzpoeschel — DISMISSED** [review]

File: src/Iteration.cpp (hunk 1 above)
Comment (franzpoeschel) [reply src/Iteration.cpp]: The issue is with the backends. I've pushed a fix for ADIOS2, still need to look into the other ones

File: src/Iteration.cpp (hunk 3 above)
Comment (ax3l) [reply src/Iteration.cpp]: Oh, thanks!
Maybe we need to note that in the doxygen string of `openIteration`

**Comment by ax3l** [comment]
I'll merge this for now, since ADIOS2 & HDF5 work, which is sufficient to unblock the 0.13.0 release #861 .

I will open a follow-up PR for ADIOS1 where we can fix that backend as well, which can go into 0.13.1/0.14.0.
