### PR TITLE
ADIOS2 fixes: Incompatibilites with current ADIOS2 master branch

### LINKED ISSUE #1163: Gracefully handle unsupported compression in current ADIOS2 master
**Describe the bug**
ADIOS2 generally throws an exception when adding an unsupported compression (e.g. adding Blosc compression when Blosc has not been compiled).
So far, we catch this exception and turn it into a warning. 

Something changed in the way ADIOS2 throws exceptions for these, so the openPMD-api currently does not catch them any more.

**Expected behavior**

Two options (we should discuss this before fixing anything):

1. Stick with the old behavior, i.e. fix the catching of the exception. This makes some CI workflows easier (which I think was the original reason I overrode the behavior of ADIOS2)
2. Change our behavior and adopt ADIOS2's behavior: Just forward the exception. This would mean that we have to fix some tests.

Opinion? @ax3l

### PR DESCRIPTION
**Pull request by franzpoeschel**
Fix #1163:

1. ADIOS2 now sometimes throws different exception types, so we must catch different types
2. ADIOS2 now throws an error if using the span-based Put() API in combination with operators, so we must adapt our tests

Notes on the second point:
* Destructing should always work, even if errors are thrown. We cannot do much against segfaults in our flushing routines during destruction, but we should check if this can be solved without leaking the memory.
* Should we add an API call `Series::invalidate()` to indicate that this `Series` object should perform no further operations (especially: only free memory during destruction, do nothing else, no flushing)?

### CODE REVIEW

File: test/SerialIOTest.cpp [hunk 1]
```diff
@@ -4427,17 +4427,23 @@ TEST_CASE( "automatically_deactivate_span", "[serial][adios2]" )
...
   }
 })END";
-        Series write( "../samples/span_based.bp", Access::CREATE, enable );
-        auto E_uncompressed = write.iterations[ 0 ].meshes[ "E" ][ "x" ];
-        auto E_compressed = write.iterations[ 0 ].meshes[ "E" ][ "y" ];
+        /*
+         * Use a pointer so we can leak the memory later.
+         * We will leave write in an invalid state and the destructor results
+         * in a segfault.
+         * This is probably a bug in itself and should be fixed.
```
Comment (ax3l) [inline test/SerialIOTest.cpp]: Is this a bug in our lib or in ADIOS2?

File: test/SerialIOTest.cpp [hunk 2]
```diff
@@ -4427,17 +4427,23 @@ TEST_CASE( "automatically_deactivate_span", "[serial][adios2]" )
...
 {
   "adios2": {
     "use_span_based_put": true
   }
 })END";
-        Series write( "../samples/span_based.bp", Access::CREATE, enable );
-        auto E_uncompressed = write.iterations[ 0 ].meshes[ "E" ][ "x" ];
-        auto E_compressed = write.iterations[ 0 ].meshes[ "E" ][ "y" ];
+        /*
+         * Use a pointer so we can leak the memory later.
```
Comment (ax3l) [inline test/SerialIOTest.cpp]: From the change I cannot see this immediately: Why is this change now necessary and wasn't before?
Due to the second point in the PR description
> ADIOS2 now throws an error if using the span-based Put() API in combination with operators, so we must adapt our tests

cc @williamfgc?
```suggestion
        /* Use a pointer so we can leak the memory later.
```

> Destructing should always work, even if errors are thrown.

Agreed.

> We cannot do much against segfaults in our flushing routines during destruction, but we should check if this can be solved without leaking the memory.

Can we potentially check which parts segfault in flush and guard them with checks? This should be related to the new operator checks, no?

> Should we add an API call `Series::invalidate()` to indicate that this `Series` object should perform no further operations (especially: only free memory during destruction, do nothing else, no flushing)?

Possible for the state of a `Series`, but that means we need to check on every member function access if the class is in valid state (and so for every other object down the dependency tree)...

File: test/SerialIOTest.cpp (hunk 1 above)
Comment (franzpoeschel) [reply test/SerialIOTest.cpp]: Probably on our side, I'm currently trying to figure it out.

File: test/SerialIOTest.cpp (hunk 2 above)
Comment (franzpoeschel) [reply test/SerialIOTest.cpp]: > Possible for the state of a Series, but that means we need to check on every member function access if the class is in valid state (and so for every other object down the dependency tree)...

Not necessarily? I would propose the following semantics for `Series::invalidate()`:
* Any access to an invalidated Series is undefined behavior
* Destruction must work

To be fair, these (repeatedly occuring) issues make me increasingly wary of putting too much logic into destructors. Sometimes, you just want to cleanly get rid of allocated memory and `invalidate()` would essentially indicate this.

Comment (franzpoeschel) [reply test/SerialIOTest.cpp]: Also, in case that you don't want to introduce this sort of undefined behavior, we can put a check on `Series::get()` which nearly every method in the Series API calls at some time.

But in my opinion, if calling something like `Series::invalidate()`, you are explicitly asking for that kind of situation, so I don't see a big problem with undefined behavior here

File: test/SerialIOTest.cpp (hunk 1 above)
Comment (franzpoeschel) [reply test/SerialIOTest.cpp]: Fixed it now, see the commit message for details

File: test/SerialIOTest.cpp (hunk 2 above)
Comment (franzpoeschel) [reply test/SerialIOTest.cpp]: > From the change I cannot see this immediately: Why is this change now necessary and wasn't before?
> Due to the second point in the PR description

Ah, I missed this part. See [this PR](https://github.com/ornladios/ADIOS2/pull/2981) and the [corresponding issue](https://github.com/ornladios/ADIOS2/issues/2965).
Previously, doing this just silently created invalid datasets and it took a lot of time to find out why they were invalid, so there is now a clear error message for that situation in ADIOS2.

Comment (williamfgc) [reply test/SerialIOTest.cpp]: @ax3l @franzpoeschel let us know if there is more of these. As much as adios2 throws exceptions, they is always a missing case. Thanks!

File: test/SerialIOTest.cpp (hunk 1 above)
Comment (ax3l) [reply test/SerialIOTest.cpp]: Ah perfect, thanks! Now we should remove this comment block again :)

File: include/openPMD/IO/AbstractIOHandlerImpl.hpp [hunk 3]
```diff
@@ -123,7 +123,7 @@ class AbstractIOHandlerImpl
                         availableChunks(i.writable, deref_dynamic_cast< Parameter< O::AVAILABLE_CHUNKS > >(i.parameter.get()));
                         break;
                 }
-            } catch (unsupported_data_error&)
+            } catch (...)
             {
                 (*m_handler).m_work.pop();
```
Comment (ax3l) [inline include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: Should we write a warning here? I think this catch should not happen in a well-defined program and could potentially complicate debugging later on if we do this silently.

File: test/SerialIOTest.cpp [hunk 4]
```diff
@@ -4469,24 +4474,28 @@ TEST_CASE( "automatically_deactivate_span", "[serial][adios2]" )
...
-    {
-        /*
-         * Using the span-based API in combination with compression is
-         * unsupported in ADIOS2.
-         * Currently, this is silently ignored, but in future there might be
-         * an error of some sort.
-         */
-        std::cerr << "Ignoring expected error: " << e.what() << std::endl;
+
+        // Leak write on purpose
```
Comment (ax3l) [inline test/SerialIOTest.cpp]:
```suggestion
```

File: test/SerialIOTest.cpp (hunk 1 above)
Comment (ax3l) [reply test/SerialIOTest.cpp]: Pushed :)

File: include/openPMD/IO/AbstractIOHandlerImpl.hpp (hunk 3 above)
Comment (franzpoeschel) [reply include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: Yep, probably a good idea and useful as a starting point for debugging. 
(Also, the current implementation has led to some quite painful debugging experiences for me, because the failing task is tried *again* upon destruction, leading to very weird error behavior. Making this change is the right call imo)

Comment (franzpoeschel) [reply include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: Another note: This code is not used by the ADIOS1 backend. Should we add the same logic there?

Comment (franzpoeschel) [reply include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: Pushed an update, current output of the test:
```
Filters: automatically_deactivate_span
[AbstractIOHandlerImpl] IO Task GET_BUFFER_VIEW failed with exception. Removing task from IO queue and passing on the exception.
Ignoring expected error: ERROR: span currently not supported with operations, remove calls to Variable<T>::AddOperation or use Variable<T>::RemoveOperations, in call to Variable<T>::Span Engine::Put
```

Note that this only removes the failing task from the IO queue but no others. We don't really do any error recovery at the moment, we already talked about improving that aspect in the future. When we do this, it will probably show which implementation makes more sense (removing only the failing task or clearing the queue).

File: include/openPMD/IO/IOTask.hpp [hunk 5]
```diff
@@ -76,6 +76,15 @@ OPENPMDAPI_EXPORT_ENUM_CLASS(Operation)
     AVAILABLE_CHUNKS //!< Query chunks that can be loaded in a dataset
 }; // note: if you change the enum members here, please update docs/source/dev/design.rst
 
+namespace internal
+{
+    /*
+     * The returned strings are compile-time constants, so no worries about
+     * pointer validity.
+     */
+    char const * operationAsString( Operation );
```
Comment (ax3l) [inline include/openPMD/IO/IOTask.hpp]: Let's use C++ types :)
```suggestion
    std::string operationAsString( Operation );
```

(`#include <string>` already part of this file)

File: src/IO/IOTask.cpp [hunk 6]
```diff
@@ -62,4 +62,84 @@ void Parameter< Operation::CREATE_DATASET >::warnUnusedParameters<
         std::cerr << warningMessage << shadow.dump() << std::endl;
     }
 }
+
+namespace internal
+{
+    char const * operationAsString( Operation op )
```
Comment (ax3l) [inline src/IO/IOTask.cpp]:
```suggestion
    std::string
    operationAsString( Operation op )
```

File: src/IO/IOTask.cpp [hunk 7]
```diff
@@ -62,4 +62,84 @@ void Parameter< Operation::CREATE_DATASET >::warnUnusedParameters<
...
+            return "LIST_ATTS";
+            break;
+        case Operation::ADVANCE:
+            return "ADVANCE";
+            break;
+        case Operation::AVAILABLE_CHUNKS:
+            return "AVAILABLE_CHUNKS";
+            break;
+        }
+        throw std::runtime_error( "Unreachable!" );
```
Comment (ax3l) [inline src/IO/IOTask.cpp]: Avoid compiler warnings:
```suggestion
        case default:
            return "unknown";
            break;
        }
```

File: include/openPMD/IO/AbstractIOHandlerImpl.hpp (hunk 3 above)
Comment (ax3l) [reply include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: > Another note: This code is not used by the ADIOS1 backend. Should we add the same logic there?

Yes, good idea. Do you like to push that in a separate PR? :)

**Review by ax3l — APPROVED** [review]
Thanks a lot! :slightly_smiling_face:

**Comment by ax3l** [comment]
Squashed for easier back-porting.

**Review by ax3l — APPROVED** [review]

File: include/openPMD/IO/AbstractIOHandlerImpl.hpp (hunk 3 above)
Comment (franzpoeschel) [reply include/openPMD/IO/AbstractIOHandlerImpl.hpp:135]: Done :) https://github.com/openPMD/openPMD-api/pull/1179
