### PR TITLE
ADIOS2: More obvious error message if datatype cannot be found

### LINKED ISSUE #1028: Incomplete error message
While debugging the Julia wrapper of openPMD-api, I received the error message below. It is incomplete, and it does not give any information about the second type.
```
LoadError: [ADIOS2] Trying to access a dataset with wrong type (trying to access dataset with type int64_t, but has type )
```

I would have expected to see a type name there, of if there is somehow no type information, say why it is missing.

**Software Environment**
 - version of openPMD-api: [0.14.0], [this](https://github.com/openPMD/openPMD-api/pull/1025) branch
 - installed openPMD-api via: [Yggdrasil]
 - operating system: [macOS 11.4]
 - machine: [laptop]
 - name and version of Python implementation: [n/a]
 - version of HDF5: [n/a]
 - version of ADIOS1: [n/a]
 - version of ADIOS2: [2.7.1]
 - name and version of MPI: [MPICH 3.4.2]

### PR DESCRIPTION
**Pull request by franzpoeschel**
Fix #1028

ADIOS2 reports datatypes as strings, and when a datatype cannot be found (e.g. when a variable is not found), it returns an empty string. The error message was a bit cryptic as a result.

New error message:
```
  [ADIOS2] Trying to access a dataset with wrong type (trying to access dataset
  with type INT, but has type UNDEFINED)
```

### CODE REVIEW

File: src/IO/ADIOS/ADIOS2IOHandler.cpp [hunk 1]
```diff
@@ -1209,10 +1209,13 @@ ADIOS2IOHandlerImpl::verifyDataset( Offset const & offset,
...
-        VERIFY_ALWAYS( requiredType == actualType,
-                       "[ADIOS2] Trying to access a dataset with wrong type (trying to "
-                       "access dataset with type " +
-                           requiredType + ", but has type " + actualType + ")" )
+        std::stringstream errorMessage;
+        errorMessage
+            << "[ADIOS2] Trying to access a dataset with wrong type (trying to "
+               "access dataset with type "
+            << determineDatatype< T >() << ", but has type "
+            << detail::fromADIOS2Type( actualType ) << ")";
```
Comment (ax3l) [inline src/IO/ADIOS/ADIOS2IOHandler.cpp]: Did you mean to add `false` here?
```suggestion
            << detail::fromADIOS2Type( actualType, false ) << ")";
```

Comment (franzpoeschel) [reply src/IO/ADIOS/ADIOS2IOHandler.cpp]: Ah yes, forgot that, thank you!

**Review by ax3l — APPROVED** [review]
